# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FIT Document Repository
email: secretary-general@internationaltouch.org
description: > # this means to ignore newlines until "baseurl:"
  Official documentation produced by the Federation of International
  Touch, the world governing body for the sport of Touch.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://docs.internationaltouch.org" # the base hostname & protocol for your site
twitter_username: intltouchorg
github_username:  internationaltouch

# Build settings
markdown: kramdown

# Add custom collections
collections:
  policy:
    output: true
    permalink: /policy/:path/
  position_description:
    output: true
    permalink: /position/:path/

defaults:
  - scope:
      path: ""
      type: policy
    values:
      layout: document
  - scope:
      path: ""
      type: position_description
    values:
      layout: document
